local explosions = require "oneroom.explosions"

local COLLISION_RESPONSE = hash("collision_response")
local EXPLOSION = hash("explosion")
local BULLET = hash("bullet")

function on_message(self, message_id, message, sender)
	if message_id == COLLISION_RESPONSE then
		if message.group == EXPLOSION or message.group == BULLET then
			explosions.large(go.get_world_position())
			go.delete()
		end
	end
end
